// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repository.Models;

[Index("ProductId", "StyleId", Name = "UQ_ProductStyles", IsUnique = true)]
public partial class ProductStyle
{
    [Key]
    public int ProductStyleId { get; set; }

    public int ProductId { get; set; }

    public int StyleId { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("ProductStyles")]
    public virtual Product Product { get; set; }

    [ForeignKey("StyleId")]
    [InverseProperty("ProductStyles")]
    public virtual Style Style { get; set; }
}