// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repository.Models;

[Table("RATING")]
public partial class Rating
{
    [Key]
    [Column("RATING_ID")]
    public int RatingId { get; set; }

    [Column("HOST")]
    [StringLength(50)]
    public string Host { get; set; }

    [Column("METHOD")]
    [StringLength(10)]
    public string Method { get; set; }

    [Column("PATH")]
    [StringLength(50)]
    public string Path { get; set; }

    [Column("REFERER")]
    [StringLength(100)]
    public string Referer { get; set; }

    [Column("USER_AGENT")]
    public string UserAgent { get; set; }

    [Column("Record_Date", TypeName = "datetime")]
    public DateTime? RecordDate { get; set; }
}