// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repository.Models;

[Index("Name", Name = "UQ__Styles__737584F640BD6215", IsUnique = true)]
public partial class Style
{
    [Key]
    public int StyleId { get; set; }

    [Required]
    [StringLength(150)]
    public string Name { get; set; }

    [StringLength(500)]
    public string Description { get; set; }

    [StringLength(500)]
    public string ImageUrl { get; set; }

    [InverseProperty("Style")]
    public virtual ICollection<ProductStyle> ProductStyles { get; set; } = new List<ProductStyle>();
}